package utility;
import openfl.Lib;
import flixel.FlxG;
import openfl.events.UncaughtErrorEvent;
import flixel.util.FlxSignal.FlxTypedSignal;
import flixel.FlxG.FlxRenderMethod;

class Systeminfo{


    


    public static function buildSystemInfo():String
    {
        var fullContents = 'Generated by: Chaos Engine\n';
    
        var driverInfo = FlxG?.stage?.context3D?.driverInfo ?? 'N/A';
        fullContents += 'Driver info: ${driverInfo}\n';
        #if sys
        fullContents += 'Platform: ${Sys.systemName()}\n';
        #end
        fullContents += 'Render method: ${renderMethod()}\n';

        fullContents += '\n';

        fullContents += '=====================\n';

        fullContents += '\n';

    

        return fullContents;
    }

    static function renderMethod():String
    {
        var outputStr:String = 'UNKNOWN';
        outputStr = try
        {
        switch (FlxG.renderMethod)
        {
            case FlxRenderMethod.DRAW_TILES: 'DRAW_TILES';
            case FlxRenderMethod.BLITTING: 'BLITTING';
            default: 'UNKNOWN';
        }
        }
        catch (e)
        {
        'ERROR ON QUERY RENDER METHOD: ${e}';
        }

        return outputStr;
    }

    #if FEATURE_DEBUG_TRACY
    /**
     * Initialize Tracy.
     * NOTE: Call this from the main thread ONLY!
     */
    public static function initTracy():Void
    {
        var appInfoMessage = buildSystemInfo();

        trace("Friday Night Funkin': Connection to Tracy profiler successful.");

        // Post system info like Git hash
        cpp.vm.tracy.TracyProfiler.messageAppInfo(appInfoMessage);

        cpp.vm.tracy.TracyProfiler.setThreadName("main");
    }
    #end
}